### ISSUE TITLE
Comonicon.jl (which uses PackageCompiler) builds ok but has a warning

### ISSUE THREAD

**Issue by KwatMDPhD** [joshday/PlotlyLight.jl#6]
![IMG_0617](https://user-images.githubusercontent.com/7741548/153515438-34f06a2a-38c1-4424-bb1d-4230e54c2ed1.jpeg)

https://github.com/KwatMDPhD/GSEA.jl v0.4.0 (there is the binary release with the warning).

You can try building `gsea` too to see the warning.

This may be due to `deps/` path issue or something related? Because `plotly.js` should be downloaded into `deps/`?

**Comment by joshday** [comment]
That's a known limitation of PackageCompiler: https://julialang.github.io/PackageCompiler.jl/dev/devdocs/relocatable_part_3.html#Relocatability-of-Julia-packages

This goes back to using artifacts for everything, which I'd like to do next week.

Note that PlotlyLight will still work out of the box, because by default it uses the Plotly.js CDN.

**Comment by joshday** [comment]
We use an artifact now!  Release is pending.
